# Generated by Django 4.1.2 on 2023-01-04 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spanishdict', '0003_spanishword_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spanishword',
            old_name='primary_eng_translation',
            new_name='eng_translation',
        ),
    ]
