# Generated by Django 4.1.2 on 2023-01-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanishdict', '0004_rename_primary_eng_translation_spanishword_eng_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spanishword',
            name='pronunciation',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
