# Generated by Django 4.1.2 on 2023-01-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanishdict', '0005_alter_spanishword_pronunciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spanishword',
            name='part_of_speech',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
