# Generated by Django 4.1.2 on 2023-01-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spanishdict', '0006_alter_spanishword_part_of_speech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spanishword',
            name='part_of_speech',
        ),
    ]
