# Generated by Django 4.1.2 on 2023-01-04 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanishdict', '0008_alter_spanishword_pronunciation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spanishword',
            name='pronunciation',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
