# Generated by Django 4.1.2 on 2023-01-13 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spanishdict', '0011_alter_spanishword_pronunciation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spanishword',
            old_name='eng_translation',
            new_name='eng',
        ),
        migrations.RenameField(
            model_name='spanishword',
            old_name='word',
            new_name='spa',
        ),
    ]
