# Generated by Django 4.1.2 on 2023-07-12 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spanishdict', '0014_spanishverb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spanishverb',
            name='conjugated_spa',
            field=models.CharField(max_length=50),
        ),
    ]
