# Generated by Django 4.1.2 on 2023-04-21 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructions',
            options={'verbose_name_plural': 'Instructions'},
        ),
        migrations.AlterField(
            model_name='article',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='img_alt',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='instructions',
            name='img_src',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
