# Generated by Django 4.1.2 on 2023-04-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itblog', '0002_alter_instructions_options_alter_article_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
